### ISSUE TITLE
error in multilib - ImportError: No module named _enigma

### ISSUE THREAD

**Issue by nautilus7** [OpenVisionE2/BackupSuite#13]
Hi, while I tested after the multib fix and it was working ok, I now get an error, which I cannot understand its origin. It seems to be triggered when the .sh script tries to access the translated strings..? I am not sure.

Here is a log created on 23/1 (working): [BackupSuite-ok.log](https://github.com/OpenVisionE2/BackupSuite/files/4114395/BackupSuite-ok.log)
And here is a today's log with the error: [BackupSuite-error.log](https://github.com/OpenVisionE2/BackupSuite/files/4114400/BackupSuite-error.log)

The error I get is:

```
Traceback (most recent call last):
  File "/usr/lib64/enigma2/python/Plugins/Extensions/BackupSuite/message.py", line 5, in <module>
  File "/usr/lib64/enigma2/python/Tools/Directories.py", line 6, in <module>
  File "/usr/lib64/enigma2/python/enigma.py", line 32, in <module>
  File "/usr/lib64/enigma2/python/enigma.py", line 24, in swig_import_helper
ImportError: No module named _enigma
```

Despite the errors, the backup seems to be completed fine though.

**Comment by persianpros** [comment]
Maybe https://github.com/OpenVisionE2/BackupSuite/blob/master/plugin/message.py#L10 is wrong.

**Comment by persianpros** [comment]
Please try again after https://github.com/OpenVisionE2/BackupSuite/commit/4e2b98d212edf97826bcf1e36845bd84cfd1b6cf

**Comment by nautilus7** [comment]
No, same issue... Do you reproduce this issue with other than English language?

**Comment by persianpros** [comment]
I can't test it myself right now, I'm not at home.

**Comment by nautilus7** [comment]
OK, I'll do more testing tomorrow. Thanks.

**Comment by persianpros** [comment]
Please test something, remove "+ ' en_EN'" in https://github.com/OpenVisionE2/BackupSuite/blob/master/plugin/plugin.py#L70~L89 and see if it works.

**Comment by 68foxboris** [comment]
Nothing changed.
/hdd/fullbackup_et1x000/20200130_2205/et1x000
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/message.py", line 5, in <module>
  File "/usr/lib/enigma2/python/Tools/Directories.py", line 6, in <module>
  File "/usr/lib/enigma2/python/enigma.py", line 21, in <module>
  File "/usr/lib/enigma2/python/enigma.py", line 20, in swig_import_helper
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    
ImportError: No module named _enigma
ls: invalid option -- 'e'
BusyBox v1.31.0 (2020-01-29 17:12:23 UTC) multi-call binary.

**Comment by persianpros** [comment]
@68foxboris 

You're using a new image which isn't Open Vision and Backup Suite can't detect it.

For OV we use https://github.com/OpenVisionE2/BackupSuite/blob/master/plugin/backupsuite.sh#L15~L27 and the rest considered as "7" (old busybox) but your busybox is new and that's why you get ls invalid option error.

This section needs to be updated by other teams not us so PRs are welcome, or maybe a check for busybox itself.

Anyway I didn't check multilib changes yet as I'm busy with 9.3 OE updates.

**Comment by athoik** [comment]
Why don't you simply check if ls supports that argument?

```
root@osmini4k:~# ls -e1 /tmp 2>/dev/null && echo yeah || echo nah
nah
root@osmini4k:~# ls -1 /tmp 2>/dev/null && echo yeah || echo nah
yeah
```

**Comment by persianpros** [comment]
As I said "or maybe a check for busybox itself" ;)

**Comment by 68foxboris** [comment]
root@et1x000:~# ls -e1 /tmp 2>/dev/null && echo yeah || echo nah
nah
root@et1x000:~# ls -1 /tmp 2>/dev/null && echo yeah || echo nah
BackupSuite.log
camd.socket
cmdwrap
duk
enigma2version
hotplug.socket
ncam.pid
oscam.log
oscam.log-prev
yeah
root@et1x000:~#

**Comment by persianpros** [comment]
Ok ls problem is solved for all: https://github.com/OpenVisionE2/BackupSuite/commit/7bd7cfa4fc65c9fae416a7fb9a31f2a4e85a3b65

**Comment by persianpros** [comment]
@nautilus7 

Would you please check multilib after https://github.com/OpenVisionE2/BackupSuite/commit/3c98b82d8ffeab25c1c83e784d739754dd621442 ?

**Comment by nautilus7** [comment]
Hi, as I mentioned here https://github.com/OpenVisionE2/BackupSuite/commit/4e2b98d212edf97826bcf1e36845bd84cfd1b6cf#comments this error happens in multilib and non multilib images as well.

I tested on a non-multilib image the latest changes and I still get the same error, but now the execution stops and no log (or backup) is created. Before, the execution was going on, producing the same error again and again, and a backup was created in the end.

**Comment by 68foxboris** [comment]
Thank you so much. Now everything works without problems.
![screenshot_19700101010527](https://user-images.githubusercontent.com/17230642/73550113-ab474780-444c-11ea-90f3-5fe92992f55d.jpg)

**Comment by nautilus7** [comment]
@persianpros  it seems to work for me now as well. Thanks.
